### ISSUE TITLE
Could you help me run ONNC 0.9.3 on the Ubuntu?

### ISSUE THREAD

**Issue by babatn1** [ONNC/onnc#114]
I already take follow this pages ( https://github.com/ONNC/onnc) from Basic instruction. but it is many errors. 
This is errors
![1](https://user-images.githubusercontent.com/39723389/47891126-dda27780-de8c-11e8-967c-9e1b54b2ad76.png)

Can you help me step by step run it? 
Thank you so much!

**Comment by tigercosmos** [comment]
please follow the [new document](https://github.com/ONNC/onnc/blob/master/docs/ONNC-Utilities.md) which might be helpful
