### ISSUE TITLE
Difference between ONNC and NNVM(TVM)

### ISSUE THREAD

**Issue by steven0129** [ONNC/onnc#116]
What is the difference between ONNC and [NNVM(TVM)](https://tvm.ai/)?

**Comment by tigercosmos** [comment]
tvm supports cpu, gpu, but we can also support DLA.

**Comment by slahss** [comment]
tvm also supports TPU-like accelerator, not just cpu, gpu.

**Comment by pliaotw** [comment]
I believe TVM should bee much mature too..
