### ISSUE TITLE
configure: error: failed to find ONNX headers

### ISSUE THREAD

**Issue by babatn1** [ONNC/onnc#118]
Hi everyone;
I am configuring ONNC following by command (../onnc/configure --with-onnx=${ONNX_DIR} \
But it appears errors 
**checking SkyPat... ok
checking ONNX... configure: error: in `/home/babatnvn/build':
configure error: failed to find ONNX headers**
See `config.log' for more details.
I had see config.log and looked that 
**configure:18933: g++ -std=c++14 -c -I/home/babatnvn/build/ONNX_DIR/include  conftest.cpp >&5
conftest.cpp:57:30: fatal error: onnx/onnx.pb.h: No such file or directory**
And I copied onnx.pb.h into onnx/onnx.pb.h folder. 
But, it is still errors above
Does anyone have an idea to fix it???

**Comment by tigercosmos** [comment]
https://github.com/ONNC/onnc/blob/master/docs/ONNC-Utilities.md
