### ISSUE TITLE
How to create a new pass?

### ISSUE THREAD

**Issue by baba1tn** [ONNC/onnc#149]
Dear everyone;

I want to create a new pass, How to can I create it? 
Please give me some of your ideas.

Many thanks

**Comment by tigercosmos** [comment]
https://github.com/ONNC/onnc/blob/10c3530d98/lib/Target/NvDla/NvDlaBackend.cpp#L110-L116

 [onnc/lib/Target/NvDla/NvDlaFileGenPass.h](https://github.com/ONNC/onnc/blob/master/lib/Target/NvDla/NvDlaFileGenPass.h)
 [onnc/lib/Target/NvDla/NvDlaFileGenPass.cpp](https://github.com/ONNC/onnc/blob/master/lib/Target/NvDla/NvDlaFileGenPass.cpp)

**Comment by baba1tn** [comment]
Hi @tigercosmos ;
The onnc/lib/Target/NvDla/NvDlaFileGenPass.cpp is a pass, right?
But var m_meta I don't know, what is it?

**Comment by tigercosmos** [comment]
```
NvDlaBackendMeta       m_pMeta;
```

`m_pMeta` stores information and it is passed by reference to be used by `Pass`es.
