### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by LinusLogics** [ONNC/onnc#161]
**Expected Result**:

**Actual Result**:
SKYPAT_LIBRARIES
    linked by target "libskypat_main" in directory /work/sunill/aireletaed/AI_ACCELERATOR/ONNC/onnc-1.2.0/tools/unittests
**Steps to reproduce**:
cmake -DCMAKE_BUILD_TYPE=Release ..
**Environment**: 

- ONNC version:1.2.0
- OS (e.g. from `python -c "import platform as p; print(p.platform());print(p.processor())"`):
- Others:

**Comment by weifen** [comment]
Suggest to follow the onnc_utility document to compile ONNC using ONNC-community docker. The issue will go away.

**Comment by LinusLogics** [comment]
Thank you , I am able to run the unit tests but I am facing the problem with single layer test.
onnc@27c49d946602:/onnc/onnc-umbrella/src/single_layer_test$ ./compile-models.sh 
./compile-models.sh: line 12: ./tools/onnc/onnc: No such file or directory

**Comment by poyenc** [comment]
hello @LinusLogics, there is a typo in the script, you can use the onnc in `PATH`

```diff
- ONNC=./tools/onnc/onnc
+ ONNC=onnc
```

**Comment by poyenc** [comment]
this issue is fixed in [`b727261`](https://github.com/ONNC/onnc/commit/b72726104396d7de550396a4b00dd0e6d8880397)
