### ISSUE TITLE
Change print() in ComputeOperator class to be virtual with default behavior

### ISSUE THREAD

**Issue by issuehsu** [ONNC/onnc#17]
In onnc/include/onnc/IR/ComputeOperator.h
class ComputeOperator
{
...
void print(std::ostream& pOS) const = 0;
...}

I suggest the print function be virtual, not pure virtual. And the default print behavior could print out the operator name and its operands. This could save lots of duplicate codes in compute nodes.

**Comment by a127a127** [comment]
For the compatibility, I don't change anything in the TG target.

After the PR merged, there will be three ways to print ComputeIR:
1. You can still override print(std::ostream) to print the format you want.
2. Just override printAttributes(std::ostream) to use the default format like this:
  `%norm1_1<float>[1, 96, 54, 54] = LRN<alpha: 0.0001, beta: 0.75, bias: 1, size: 5>(%conv1_2<float>[1, 96, 54, 54])`
3. Do nothing, will print something like:
  `%norm1_1<float>[1, 96, 54, 54] = MyOperaoter<unimplemented>(%conv1_2<float>[1, 96, 54, 54])`

If there are anything I can help, feel free to let me know.

**Comment by a127a127** [comment]
Done by #81 .
Feel free to reopen it if there are any further issues.
