### ISSUE TITLE
onnx namespace problem

### ISSUE THREAD

**Issue by ffk0716** [ONNC/onnc#18]
Should I use "::ONNX_NAMESPACE::Foo" or "::onnc::xFoo"?

I Have tried "xFoo" and found many problems....

1. type generated by protobuf does not defined in ONNX.h

There are lots of type generated by protobuf, ex ::onnx::NodeProto
But I can't find xNodeProto in ONNX.h

2. enum of onnx does not support?

ex onnx::TensorProto_DataType_INT8
If I use "kInt8" I got:
error: cannot convert ‘onnc::xValueType’ to ‘bm_onnx::TensorProto_DataType’ in assignment
Should I use "(xTensorProtoDataType)kInt8" in any place?

**Comment by lubatang** [comment]
1. Please use onnc::xFoo. If the type was not defined in ONNX.h.in.
If there is a type you needed but not defined in ONNX, you can add it and create another PR.
ONNX.h.in collects all explaining types of ONNX.

2. yes. C/C++ doesn't support constant alias yet. You have to cast enum class like that.
