### ISSUE TITLE
There are some compiling errors in Compute and TensorSel folder.

### ISSUE THREAD

**Issue by JerryShih** [ONNC/onnc#53]
We already added all .cpp files into CMakelist in Compute and TensorSel folder(#50), but there are some compiling errors in the following files:

Compute/Constant.cpp
Compute/If.cpp
Compute/Loop.cpp
TensorSel/ConstantLower.cpp
TensorSel/IfLower.cpp
TensorSel/LoopLower.cpp

@lubatang

**Comment by JerryShih** [comment]
I think those errors are not related to the build system.

**Comment by lubatang** [comment]
IMHO, we shall erase these files from the building list for a while.

**Comment by JerryShih** [comment]
Those files are already commented in cmakelist in #50.
