### ISSUE TITLE
exception of std::length_error: vector in unittest

### ISSUE THREAD

**Issue by lubatang** [ONNC/onnc#55]
When running unittest `SKYPAT_F(TensorSelTest, alexnet)`, I got an exception
```
[RemoveTrainingNodes] changed
[UpdateGraphOutputSize] changed
[DeadNodeElimination] changed
[BookONNXGraphs] changed
[BuildInitializers] changed
[BuildInputOperators] changed
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
Abort trap: 6
```

lldb locates the bug in line 70.
```
 69       xValue &input = *m_Node.inputs()[0];
 70       std::vector<int64_t> v(input.sizes().size() - 2, 1);
 71       pOp.setDilations(std::move(v));
 ```

I guess input.sizes() contains less than two elements.

**Comment by a127a127** [comment]
It's not possible.
The input.sizes().size() should be greater than 2 by definition. I will add an assertion.
It seems there was some bug before this pass, I will looking into it.

**Comment by a127a127** [comment]
It should work fine after PR #69 (And you should upgrade ONNX to 1.3 at local).
