### ISSUE TITLE
When to publish some codes about NVDLA？

### ISSUE THREAD

**Issue by JSnobody** [ONNC/onnc#71]
Hi，
I find the target NVDLA you will support in document，In-depth Compiler Technical Experience.
And I tried to find codes about NVDLA in your project，but I could not find them.
So, I think you have not publish somes codes about NVDLA.
Do you plan to publish them?
Thank you!.

**Comment by tigercosmos** [comment]
already in the source

**Comment by JSnobody** [comment]
Thanks very much！

**Comment by wxbbuaa2011** [comment]
How to use this compiler? Is there a document explanation?

**Comment by wxbbuaa2011** [comment]
@JSnobody  I also study NVDLA, I hope to have the opportunity to communicate with you.

**Comment by tigercosmos** [comment]
There are some documents in [docs](https://github.com/ONNC/onnc/blob/master/docs/). Please check if they meet your need.
If you want to evaluate the ONNC compiler for NVDL
A, you can follow the document, [ONNC-Utilities.md](https://github.com/ONNC/onnc/blob/master/docs/ONNC-Utilities.md), to set up the environment.

Then run:
```
./tools/onnc/onnc /models/bvlc_alexnet/model.onnx -mquadruple nvdla
```

There is ` out.nvdla` as the output.
