### ISSUE TITLE
unittests failed at parsing onnx input file

### ISSUE THREAD

**Issue by evenpengqnap** [ONNC/onnc#9]
I compiled and installed onnc with umbrella.
The unittests failed at "1 test from TensorSelTest" with `Error: Cannot parse onnx input file /workspace/onnc-umbrella/src/tools/unittests/data/bvlc_alexnet/model.onnx`.
I had tried to use command `/opt/onnc/bin/readonnx` and failed.
Besides, I cannot parse the other two models, either.
```
/workspace/onnc-umbrella/src/tools/unittests/data/lenet/model.onnx
/workspace/onnc-umbrella/src/tools/unittests/data/mnist/model.onnx
```
But I can parse own onnx file.
Any idea?
Thanks!

**Comment by evenpengqnap** [comment]
I download the onnx file from [model zoo](https://github.com/onnx/models/tree/master/bvlc_alexnet) and put it to the directory of unittests.
The onnx file can be parsed and some Passes are executed.
But it failed with following message:
```
RemoveTrainingNodes
UpdateGraphOutputSize
DeadNodeElimination
BookONNXGraphs
BuildInitializers
BuildInputOperators
terminate called after throwing an instance of 'std::bad_alloc'
  what(): std::bad_alloc
Aborted
```

**Comment by a127a127** [comment]
I think it's due to the ONNX shape inference issues as issue #15.
After PR #69 , it should works fine.

I close this issue for now.
If it still doesn't work, feel free to reopen this issue or create a new issue.

Thanks for the report this issue <(_ _)>
